spring:
  application:
    name: "order"
  grpc:
    server:
      port: 9093
    client:
      channels:
        payment:
          address: 0.0.0.0:9094
        inventory:
          address: 0.0.0.0:9091
credentials:
  order-system-secret: ${ORDER_SYSTEM_TOKEN}
  client-system-secret: ${CLIENT_SYSTEM_TOKEN}